name: fankaixinxu
on:
  workflow_dispatch:

  schedule:
    - cron: '6 2,8,14,20 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: fankaixinxu
        env:
          xyxuv774: ${{ secrets.xyxuv774 }}
        run: |
          printf '%s' "$xyxuv774" | jq -r .yhrh6539 | /bin/bash
          echo $drij2 | jq -r .mu51 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: zJl9ASy4
          path: "*.zip"
          retention-days: 1
